#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

for f in /etc/rc.d/init.d/*
do
	# Ignore dangling symlinks
	[ ! -f "$f" ] && continue
	$f start
done

# Start all init scripts in /etc/init.d
# executing them in numerical order
for i in /etc/init.d/S???* ;do
	# Ignore dangling symlinks
	[ ! -f "$i" ] && continue

	case "$i" in
	*.sh)
		# Source shell script for speed
		(
		trap - INT QUIT TSTP
		set start
		. $i
		)
		;;
	*)
		# No sh extension, so fork subprocess
		$i start
		;;
	esac
done
