#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Initialize the hostname

case "$1" in
	start)
		echo "Initializing hostname...\r"
		exec 2>&1
		exec hostname -F /etc/hostname
		echo "Hostname initialized $(hostname)"
		;;
	*)
		echo $"Usage: $0 start"
		exit 1
esac

exit $?
